In [1]:
# Remove doublings from table and estimate them
# FM 20/10/2025

In [2]:
import sys
sys.path.append('amos') 
# Import all ML orchestration functions
from amos.ml_orchestration import (
    ml_exp_with_timing,  # Main experiment function with timing preservation
    extract_timing_structure,
    save_midi_with_exact_timing_structure,
    KerasClassifierWrapper,
    build_lstm_classifier,
    build_transformer_classifier,
    clf_predict,
    defineXy,           # Data preparation function
    split_and_encode    # Train/test split with encoding
)
# Import MIDI processing functions  
from amos.midi2df2midi import midi_to_dataframe, save_midi_from_df
from amos.mappings import fill_quaterna_columns, learn_quaterna_mapping
# Import amo funtion
from amos.ml_orchestration import amo

import pandas as pd
import numpy as np_orch
from collections import defaultdict

/home/francesco/anaconda3/envs/auto-orch/lib/python3.12/site-packages/xgboost/core.py:377: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc >= 2.28) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(
2025-10-20 13:07:03.517276: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [3]:
fileorch='midis/liszt_classical_archives-0/orchestra.mid'

In [4]:
print(f"Orchestra file: {fileorch}")
dforch = midi_to_dataframe(fileorch)
dforch = dforch.sort_values(
    ['onset in quarter notes', 'duration in quarter notes', 'track number'],
    ascending=[True, True, True]
)
print(dforch.columns)
print("Table:\n", dforch)
np_orch = dforch.to_numpy()
mapping = learn_quaterna_mapping(np_orch, ytarget="track-channel")
print("Mapping:", mapping)

Orchestra file: midis/liszt_classical_archives-0/orchestra.mid
Index(['track number', 'track name', 'channel', 'program',
       'onset in quarter notes', 'duration in quarter notes', 'pitch',
       'velocity'],
      dtype='object')
Table:
       track number   track name  channel  program  onset in quarter notes  \
0                1        Flute        1       73                     0.0
1                1        Flute        1       73                     0.0
585              2         Oboe        2       68                     0.0
586              2         Oboe        2       68                     0.0
1206             3     Clarinet        3       71                     0.0
...            ...          ...      ...      ...                     ...
1205             2         Oboe        2       68                  1574.0
4791            10       Violin       10       40                  1574.0
5491            11        Viola       11       41                  1574.0
6080            12  Violoncello       12       42                  1574.0
6616            13   Contrabass       13       43                  1574.0

      duration in quarter notes  pitch  velocity
0                           2.0     82        60
1                           2.0     88        60
585                         2.0     70        60
586                         2.0     76        60
1206                        2.0     67        60
...                         ...    ...       ...
1205                        1.0     79        60
4791                        1.0     67        60
5491                        1.0     63        60
6080                        1.0     46        60
6616                        1.0     34        60

[6617 rows x 8 columns]
Mapping: [[1 'Flute' 1 73]
 [2 'Oboe' 2 68]
 [3 'Clarinet' 3 71]
 [4 'Bassoon' 4 70]
 [5 'Horn' 5 60]
 [6 'Trumpet' 6 56]
 [9 'Violin' 10 40]
 [10 'Violin' 10 40]
 [11 'Viola' 11 41]
 [12 'Violoncello' 12 42]
 [13 'Contrabass' 13 43]]

In [5]:
def reduce_df_with_transform(df, tol=1.0, transformations=None):
    df_reduced = df
    df_hashed = defaultdict(list)
    count_match = {
        'transformed': 0,
        'direct': 0
    }

    for func, kwargs in transformations:
        df_reduced[f"{func.__name__}_{kwargs}"] = False

    todrop = []

    for idx, note in df_reduced.iterrows():
        key = (note['onset in quarter notes'], note['pitch'])        

        matched = False
        if transformations:
            for func, kwargs in transformations:
                if not matched:
                    transformed = func(note, **kwargs)
                    for t in transformed:
                        key_t = (t['onset in quarter notes'], t['pitch'])
                        if len(df_hashed[key_t]) > 0: # if something matches with the transformation
                            for candidate_match_index in df_hashed[key_t]:
                                candidate_match = df_reduced.loc[candidate_match_index]
                                dur_diff = abs(candidate_match['duration in quarter notes'] - note['duration in quarter notes'])
                                if dur_diff <= note['duration in quarter notes'] * tol:
                                    df_reduced.at[candidate_match_index, f"{func.__name__}_{kwargs}"] = True
                                    matched = True
                                    count_match['transformed'] += 1
                                    todrop.append(idx)
                                    break
                            if not matched:
                                df_hashed[key_t].append(idx)
                                matched = True
                                count_match['direct'] += 1
                                break

        if not matched:
            df_hashed[key].append(idx)
            count_match['direct'] += 1

    print(count_match)
    print(f"Original size: {df_reduced.shape}")
    print(f"Dropping {todrop}")
    df_reduced.drop(todrop, inplace=True)
    print(f"Size after drop: {df_reduced.shape}")

    return df_reduced

In [6]:
def transpose(note, n_semitones=12):
    # Example: transpose pitch
    new_note = note.copy()
    new_note['pitch'] = note['pitch'] + n_semitones
    return [ new_note ]

In [7]:
def split_duration(note, smallest_unit=1.0):
    # Split a note into a set of notes of duration smallest_unit
    # ['track number', 'track name', 'channel', 'program', 'onset in quarter notes', 'duration in quarter notes', 'pitch', 'velocity']
    transformed_notes = []
    dur = note['duration in quarter notes']
    n = int(dur // smallest_unit)
    for i in range(n):
        new_note = note.copy()
        new_note['onset in quarter notes'] = note['onset in quarter notes'] + smallest_unit*i
        new_note['duration in quarter notes'] = smallest_unit
        transformed_notes.append(new_note)
    if dur - smallest_unit*n > 0:
        new_note = note.copy()
        new_note['onset in quarter notes'] = note['onset in quarter notes'] + smallest_unit*n
        new_note['duration in quarter notes'] = dur - smallest_unit*n
        transformed_notes.append(new_note)
    return transformed_notes

In [8]:
transformations = [
    (transpose, {'n_semitones': 12}),
    (transpose, {'n_semitones': 24}),
    (transpose, {'n_semitones': 46}),
    (transpose, {'n_semitones': -12}),
    (transpose, {'n_semitones': -24}),
    (transpose, {'n_semitones': -46}),
    #(split_duration, {'smallest_unit': 0.25}),
]

In [9]:
df_reduced = reduce_df_with_transform(dforch, tol=0.2, transformations=transformations)

{'transformed': 2511, 'direct': 4106}
Original size: (6617, 14)
Dropping [585, 586, 1207, 1676, 2776, 2777, 3775, 3776, 4792, 5492, 2370, 587, 588, 1208, 1209, 1678, 2778, 2779, 2780, 3777, 3778, 4793, 5493, 589, 1211, 1680, 2371, 2781, 2782, 2783, 3779, 3780, 3781, 4794, 5494, 591, 1212, 1213, 1682, 2374, 2784, 2785, 2786, 3782, 3783, 3784, 4795, 5495, 593, 594, 1215, 1684, 2375, 2787, 2788, 2789, 3785, 3786, 6085, 595, 596, 1217, 1686, 2376, 2790, 2791, 2792, 3787, 3788, 4797, 6086, 597, 598, 1219, 1688, 2377, 2793, 2794, 2795, 3789, 3790, 4798, 6087, 599, 600, 1220, 1221, 1690, 2378, 2628, 2629, 2796, 2798, 3791, 3793, 4799, 6088, 3794, 3795, 3796, 3797, 3798, 2381, 1222, 3799, 3800, 1693, 3801, 1696, 3802, 3803, 3804, 1698, 3805, 3806, 3807, 3808, 5507, 3809, 1703, 2382, 2383, 3810, 1223, 1224, 1705, 2384, 2385, 3811, 3812, 1225, 1707, 2386, 2387, 3813, 3814, 1226, 3815, 3816, 1227, 5513, 3817, 3818, 3819, 3820, 1228, 1229, 1714, 3821, 4812, 1230, 1231, 1715, 3822, 4813, 1232, 1233, 3823, 4814, 1234, 1235, 3824, 4815, 1236, 1237, 1718, 2390, 2391, 3826, 4816, 5517, 617, 618, 1238, 1239, 1720, 2392, 2393, 2630, 2631, 5518, 6106, 619, 620, 1240, 1722, 2394, 2395, 2633, 621, 622, 1242, 1243, 2396, 2397, 2836, 2837, 3831, 1724, 2635, 6107, 623, 624, 1244, 1245, 2398, 2399, 2838, 3832, 625, 626, 1246, 1247, 1726, 2400, 2401, 2839, 3833, 627, 628, 1248, 1249, 2402, 2403, 2840, 3834, 629, 630, 1250, 1251, 2404, 2405, 2841, 3835, 631, 632, 1730, 2406, 2842, 3836, 6109, 633, 1732, 2408, 2845, 3837, 3839, 6110, 634, 635, 1254, 1255, 1734, 2411, 2636, 2637, 4823, 4824, 5524, 6111, 636, 637, 1256, 1736, 2413, 2638, 2639, 6112, 1258, 2414, 2415, 2641, 639, 1737, 2417, 2419, 640, 641, 1261, 1262, 1740, 2421, 642, 643, 1264, 2422, 5526, 6113, 5527, 6114, 5528, 6115, 5529, 6116, 5530, 6117, 5531, 6118, 2859, 3853, 4833, 6119, 644, 645, 1265, 1266, 5534, 6120, 5535, 6121, 6122, 6123, 6124, 5539, 6125, 1745, 1267, 4840, 4841, 1269, 1749, 3862, 6130, 6131, 6132, 6133, 5546, 6134, 1271, 1751, 2901, 3867, 4847, 6135, 1273, 2426, 5548, 6136, 1272, 6137, 5550, 6138, 5551, 6139, 5552, 5553, 5554, 6142, 6143, 6145, 5557, 6146, 5558, 1274, 1755, 1757, 2918, 3876, 4854, 6148, 1759, 2919, 3877, 4855, 6149, 1275, 1276, 1761, 2427, 2428, 2920, 3878, 4856, 6150, 1763, 2929, 3879, 4857, 6151, 3880, 4858, 5563, 1765, 659, 1278, 2429, 2430, 2642, 2643, 661, 1280, 1767, 2431, 2432, 2644, 2645, 5564, 5565, 662, 1281, 1282, 1769, 2647, 2433, 5566, 1283, 1284, 1771, 2648, 2649, 2940, 3890, 4862, 665, 666, 1285, 1286, 2435, 2436, 2650, 2651, 4863, 6157, 3892, 3893, 3894, 4868, 3895, 667, 2437, 2438, 4874, 669, 2439, 2440, 4876, 3896, 3897, 1781, 3899, 3901, 1288, 1784, 2953, 3903, 3904, 3905, 1289, 1787, 3907, 2652, 2653, 3909, 4889, 1290, 1789, 3911, 2654, 2655, 1291, 1292, 3913, 1293, 1792, 678, 1294, 1794, 2447, 2448, 2657, 2965, 3915, 4895, 2966, 3916, 3917, 3918, 3919, 3920, 3921, 3922, 3923, 679, 1295, 1296, 1800, 2449, 2450, 4906, 3924, 3925, 681, 1297, 1298, 1802, 2451, 2452, 4908, 3926, 3927, 683, 1299, 1300, 1803, 2453, 2454, 4909, 3928, 1301, 1805, 2980, 3929, 1302, 1806, 3930, 1303, 1808, 1304, 1809, 3932, 1305, 1811, 1306, 1812, 3934, 3935, 1307, 1814, 1308, 1816, 3936, 4919, 1309, 1818, 3938, 5596, 1310, 1819, 2658, 2659, 3940, 4923, 1311, 1821, 1312, 1823, 3942, 2660, 2661, 1313, 1824, 2996, 3944, 5599, 692, 1314, 1826, 2461, 2462, 2663, 2997, 3946, 3947, 3948, 3949, 3950, 693, 1315, 3002, 3951, 4929, 694, 1316, 3003, 3952, 4930, 695, 1317, 3004, 3953, 4931, 5602, 3954, 3955, 3956, 3957, 696, 1318, 3009, 3958, 4932, 697, 1319, 3010, 3959, 4933, 1320, 1832, 3960, 4934, 5605, 1321, 1833, 3961, 4935, 5606, 1322, 1834, 3962, 4936, 5607, 1323, 1835, 3963, 4937, 5608, 1324, 1836, 3964, 4938, 5609, 1325, 1837, 3965, 4939, 5610, 1326, 1838, 3966, 4940, 5611, 1327, 1839, 3967, 4941, 5612, 1328, 1840, 3968, 4942, 5613, 1329, 1841, 3969, 4943, 5614, 1330, 1842, 3970, 4944, 5615, 1331, 1843, 3971, 4945, 5616, 1332, 1844, 3972, 4946, 5617, 1333, 1845, 3973, 4947, 5618, 1334, 1846, 3974, 4948, 5619, 5620, 713, 1335, 2464, 3026, 3975, 5621, 5622, 1336, 1337, 2465, 2466, 5623, 5624, 1338, 1339, 2467, 2468, 5625, 6174, 1340, 1341, 2470, 2665, 3027, 3028, 3976, 5626, 6175, 714, 1848, 715, 1849, 716, 1850, 2667, 3030, 4956, 717, 1851, 3031, 3978, 718, 1852, 719, 1853, 5628, 720, 2669, 3033, 3980, 3981, 3982, 5629, 1342, 1343, 2472, 4959, 5631, 1344, 1345, 2473, 2474, 5632, 5633, 1346, 1347, 2475, 2476, 5634, 6178, 1348, 1349, 2478, 2671, 3036, 3037, 3983, 5635, 6179, 721, 1855, 722, 1856, 723, 1857, 5636, 724, 1858, 3040, 3985, 725, 1859, 726, 1860, 5637, 6181, 727, 1350, 1861, 2673, 3042, 3987, 3988, 3989, 5638, 728, 1351, 1352, 1863, 1864, 2479, 2480, 2674, 2675, 4968, 5639, 5640, 6182, 3990, 5641, 5642, 730, 1353, 1354, 1866, 2481, 2482, 2676, 2677, 5643, 3993, 3994, 3995, 4973, 5644, 6183, 732, 1355, 1356, 1867, 1868, 2483, 2484, 2678, 2679, 4974, 5645, 5646, 6184, 3996, 5647, 5648, 734, 1357, 1358, 1870, 2485, 2486, 2680, 2681, 5649, 6185, 1871, 2487, 2682, 2683, 4979, 5650, 3061, 4983, 5654, 1360, 1361, 3065, 4012, 5655, 1362, 1363, 6188, 1364, 1365, 4014, 5657, 1366, 1367, 4015, 5658, 1368, 1369, 6190, 1370, 1371, 4017, 5660, 1372, 1373, 4990, 5661, 1882, 3072, 4019, 5662, 758, 3074, 6192, 5664, 4023, 6195, 4024, 4025, 4026, 4027, 3080, 759, 760, 761, 762, 763, 4029, 4030, 4031, 4032, 3085, 4034, 6196, 4999, 5670, 764, 765, 4035, 766, 767, 1898, 1899, 4036, 6197, 5672, 4037, 768, 769, 1900, 1901, 770, 771, 1902, 1903, 4038, 6199, 4039, 772, 773, 1904, 1905, 3092, 4040, 5004, 774, 775, 1906, 1907, 3093, 4041, 5676, 776, 777, 1908, 1909, 3094, 4042, 5006, 5677, 778, 779, 1910, 1911, 3095, 4043, 6203, 1390, 780, 781, 1912, 1913, 3096, 4044, 782, 783, 1915, 2489, 2684, 3097, 4045, 4046, 5008, 5680, 4047, 4048, 784, 785, 1392, 2685, 5684, 786, 787, 1394, 1918, 1919, 5685, 788, 4049, 5015, 789, 4050, 5017, 790, 4051, 791, 4052, 5019, 3108, 4053, 1920, 3110, 4055, 4057, 4058, 793, 794, 1921, 1922, 4059, 795, 796, 1923, 1924, 4061, 797, 4063, 5021, 798, 4064, 5023, 799, 4065, 800, 4066, 5025, 4067, 801, 1395, 6215, 2687, 4068, 4069, 4070, 802, 1396, 4071, 6216, 803, 1397, 4072, 6217, 804, 1398, 1928, 4073, 5029, 5698, 805, 1399, 4074, 6219, 806, 1400, 4075, 6220, 4076, 1401, 6221, 809, 1403, 3136, 4080, 6222, 810, 1404, 3137, 4081, 6223, 811, 1405, 3138, 4082, 6224, 812, 1406, 3139, 4083, 6225, 813, 1407, 3140, 4084, 6226, 814, 1408, 3141, 4085, 6227, 815, 1409, 3142, 4086, 5039, 6228, 250, 1939, 5709, 6229, 252, 5041, 6230, 254, 5042, 6231, 256, 5043, 6232, 258, 5044, 6233, 260, 5045, 6234, 262, 5046, 6235, 824, 1418, 2493, 3150, 6236, 826, 1420, 2495, 2689, 3151, 1421, 2496, 2690, 3152, 4097, 5048, 1423, 2497, 2691, 3153, 4098, 4099, 5049, 5719, 4103, 6240, 6242, 6243, 6245, 6246, 6247, 6250, 6251, 6252, 3170, 6253, 6254, 3171, 6255, 6257, 1954, 6258, 6260, 1955, 6261, 1956, 5750, 6264, 1957, 1958, 6268, 841, 842, 1426, 1959, 6269, 6271, 5082, 6272, 1961, 1428, 5083, 5084, 5085, 6274, 6275, 6276, 6277, 6278, 1430, 1965, 1966, 6279, 6280, 6281, 5090, 5772, 6282, 848, 1967, 3194, 6283, 6284, 2500, 2693, 6285, 849, 1969, 1970, 4141, 851, 1971, 1972, 4142, 853, 1973, 1974, 4143, 6286, 6287, 2502, 2695, 6288, 855, 1975, 1976, 4144, 857, 1977, 1978, 4145, 4146, 859, 1979, 1980, 4147, 4148, 4149, 4150, 861, 1434, 1435, 5097, 6289, 4151, 4152, 4153, 4154, 863, 1436, 1437, 1982, 5098, 5780, 4155, 4156, 4157, 4158, 865, 1438, 1439, 5100, 6291, 4159, 4160, 4161, 4162, 5101, 5782, 867, 1985, 4163, 4164, 6293, 4165, 4166, 5784, 6294, 4167, 4168, 5785, 6295, 4169, 4170, 5786, 6296, 869, 4171, 4172, 5787, 6297, 4173, 4174, 5788, 6298, 4175, 4176, 5789, 6299, 4177, 4178, 5790, 6300, 871, 872, 1989, 4179, 4180, 5791, 6301, 4181, 4182, 6302, 4183, 4184, 5793, 6303, 4185, 4186, 873, 1990, 5794, 6304, 4187, 4188, 874, 1991, 5795, 4189, 4190, 875, 1992, 4191, 4192, 876, 1994, 4193, 4194, 1995, 5115, 5796, 877, 5116, 5798, 6308, 2000, 2001, 5118, 5799, 298, 2002, 2003, 5119, 5800, 300, 2004, 2005, 5120, 5801, 5121, 5802, 302, 1442, 2006, 2007, 5803, 5123, 5804, 304, 1444, 2008, 2009, 2503, 2504, 2696, 5805, 5125, 5806, 306, 1446, 2010, 2011, 2505, 2506, 2698, 5807, 308, 1448, 2012, 2013, 2507, 5127, 5808, 310, 1450, 2014, 2015, 4221, 5128, 5809, 2509, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 312, 1452, 2029, 5810, 6324, 314, 902, 1454, 2030, 3282, 4235, 5130, 5811, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 316, 1456, 2044, 2045, 2702, 4248, 5812, 6326, 918, 2046, 2047, 2703, 4249, 5132, 5813, 1458, 2048, 2049, 1460, 1461, 3290, 1462, 1463, 3291, 923, 1464, 1465, 2050, 2051, 3292, 925, 1466, 1467, 2052, 2053, 2704, 3293, 5814, 6328, 927, 2054, 2055, 4255, 5815, 6329, 1469, 3294, 2518, 2056, 2057, 1470, 1471, 3295, 1472, 1473, 3296, 931, 1474, 1475, 2058, 2059, 3297, 933, 1476, 1477, 2060, 2061, 3298, 3300, 4260, 4261, 5135, 5816, 6330, 1478, 1479, 2064, 2065, 2520, 2521, 935, 1480, 1481, 2067, 2523, 936, 1482, 1483, 2069, 2525, 937, 1484, 1485, 2071, 938, 1486, 2073, 940, 1487, 2075, 942, 1488, 2077, 4262, 5136, 5817, 6333, 6334, 6335, 5821, 6336, 2078, 1489, 4267, 5141, 5142, 5143, 5823, 6339, 1491, 2082, 3323, 4270, 6340, 6341, 6342, 6343, 5828, 6344, 1493, 2084, 3341, 4275, 5149, 6345, 1495, 2526, 1494, 5830, 6347, 5832, 5834, 4282, 5835, 1496, 2088, 2090, 3357, 4283, 5160, 6354, 2092, 3358, 4284, 5161, 6355, 1497, 1498, 2094, 2527, 2528, 3359, 4285, 5162, 6356, 2096, 3368, 4286, 5163, 6357, 4287, 5164, 5840, 2098, 957, 1500, 2529, 2530, 2707, 2708, 958, 1502, 2100, 2710, 2531, 4294, 5165, 5841, 5842, 5843, 6361, 1503, 1504, 2102, 2711, 2712, 3379, 4297, 5168, 961, 962, 1505, 1506, 2533, 2534, 2713, 2714, 4299, 5846, 4301, 963, 2535, 2536, 5849, 4302, 1507, 2108, 3387, 4303, 5850, 1508, 2111, 3388, 4305, 4306, 4307, 5852, 1509, 2113, 4309, 1510, 1511, 4311, 1512, 2116, 968, 1513, 2117, 2539, 2540, 2718, 5189, 4313, 5855, 4314, 4315, 4316, 4317, 4318, 4319, 4320, 969, 1514, 1515, 2119, 2541, 2542, 4321, 4322, 4323, 4324, 1516, 2121, 4325, 5857, 1517, 2123, 1518, 2124, 4327, 5858, 1519, 2126, 1520, 2127, 4329, 4330, 5859, 1521, 2129, 1522, 2131, 4331, 5201, 5860, 1523, 2133, 4333, 1524, 2135, 4335, 5205, 2719, 2720, 1525, 2137, 4337, 1526, 2139, 4339, 5209, 2721, 2722, 1527, 2141, 3424, 4341, 4342, 1528, 2142, 2723, 2724, 4343, 1529, 2144, 4345, 2145, 2146, 2551, 2552, 5867, 4346, 4347, 4348, 4349, 4350, 4351, 2147, 5216, 5868, 4352, 4353, 4354, 982, 1532, 3438, 4355, 5217, 983, 1533, 3439, 4356, 5218, 5870, 1534, 2150, 4357, 5219, 5871, 1535, 2151, 4358, 5220, 5872, 1536, 2152, 4359, 5221, 5873, 1537, 2153, 4360, 5222, 5874, 1538, 2154, 4361, 5223, 5875, 1539, 2155, 4362, 5224, 5876, 1540, 2156, 4363, 5225, 5877, 1541, 2157, 4364, 5226, 5878, 1542, 2158, 4365, 5227, 5879, 1543, 2159, 4366, 5228, 5880, 1544, 2160, 4367, 5229, 5881, 5882, 1545, 2161, 2553, 2554, 4368, 5883, 5884, 1546, 1547, 2556, 5885, 5886, 1548, 1549, 2557, 2558, 5887, 5888, 1550, 1551, 2559, 2560, 5889, 2562, 2728, 3452, 3453, 4369, 5890, 996, 2162, 997, 2163, 998, 2164, 999, 2165, 1000, 2166, 5891, 1001, 2730, 3455, 5892, 5893, 1554, 1555, 2564, 5894, 5895, 1556, 1557, 2565, 2566, 5896, 5897, 1558, 1559, 2567, 2568, 5898, 2570, 2731, 4375, 5247, 5899, 1002, 2168, 1003, 2169, 1004, 2170, 3462, 4378, 4379, 4380, 5900, 1005, 2171, 1006, 2172, 5249, 5901, 1007, 1562, 2174, 2733, 2734, 3464, 5902, 5903, 1008, 1563, 1564, 2175, 2571, 2572, 2736, 5904, 5905, 5906, 5907, 1010, 1565, 1566, 2178, 2573, 2574, 2737, 2738, 5908, 5909, 5910, 5911, 1012, 1567, 1568, 2179, 2575, 2576, 2740, 5912, 5913, 5914, 5915, 1014, 1569, 1570, 2182, 2577, 2578, 2741, 2742, 5916, 1016, 1571, 1572, 2183, 2184, 2579, 2580, 2743, 2744, 3476, 4393, 5265, 2185, 2581, 2745, 2746, 5266, 5918, 1019, 1574, 2583, 2584, 2747, 2748, 3482, 4399, 5267, 5919, 3486, 5271, 5923, 1575, 1576, 3490, 4408, 5924, 1577, 4410, 1579, 1580, 1581, 1582, 4412, 5928, 5276, 5929, 1036, 3496, 4416, 4417, 4418, 4419, 4420, 3502, 1037, 1038, 1039, 4422, 4423, 4424, 4425, 3507, 4427, 5283, 5936, 1040, 1041, 4428, 4429, 6469, 1042, 1043, 2205, 2206, 4430, 5938, 1044, 1045, 2207, 2208, 5286, 5939, 4431, 1046, 1047, 2209, 2210, 4432, 4433, 1048, 1049, 2211, 2212, 3515, 4434, 5289, 1050, 1051, 2213, 2214, 3516, 4435, 5290, 5943, 1052, 1053, 1594, 2215, 2216, 3517, 4436, 1054, 1055, 1596, 2217, 2218, 3518, 4437, 3520, 4438, 1056, 1597, 2220, 2585, 3522, 4440, 3524, 4442, 3526, 4444, 3528, 4446, 4448, 1058, 1599, 1600, 2222, 4450, 4452, 1060, 1601, 1602, 2224, 5952, 4454, 4456, 5954, 4458, 4460, 5305, 1062, 4462, 5307, 1063, 4463, 5309, 1064, 4464, 5959, 5311, 1065, 4465, 3548, 4466, 2225, 2588, 3550, 4468, 3552, 4470, 3554, 4472, 3556, 4474, 4476, 1067, 1068, 2226, 2227, 4478, 4480, 4482, 1069, 1070, 2228, 2229, 5968, 4484, 6504, 4486, 4488, 4490, 5324, 1071, 4492, 5326, 1072, 4493, 4494, 1073, 1603, 2755, 5974, 4495, 4496, 1074, 1604, 2231, 5975, 4497, 4498, 1075, 1605, 4499, 4500, 1076, 1606, 4501, 4502, 1077, 1607, 6518, 4518, 1084, 1614, 2240, 5984, 501, 503, 5986, 505, 507, 6524, 1090, 1620, 2592, 2756, 3608, 1091, 1621, 1622, 2593, 2757, 3609, 4529, 5989, 4532, 6528, 6529, 3615, 5996, 6000, 2248, 6001, 2250, 1099, 1100, 1624, 2251, 5361, 2253, 1626, 1628, 2257, 2258, 6019, 1106, 2259, 3633, 2596, 2759, 1107, 2261, 2262, 4557, 1109, 2263, 2264, 4558, 2598, 2761, 1111, 4559, 2266, 1113, 4560, 2268, 4561, 1115, 2269, 2270, 4562, 4563, 4564, 1117, 1632, 1633, 4565, 4566, 4567, 4568, 1119, 1634, 1635, 2272, 6027, 4569, 4570, 4571, 5377, 4572, 1121, 1636, 1637, 4573, 4574, 4575, 4576, 1123, 2275, 4577, 4578, 4579, 4580, 4581, 4582, 4583, 1125, 2277, 5380, 6031, 4584, 4585, 4586, 1127, 2278, 6032, 6570, 4587, 4588, 1128, 2279, 4589, 4590, 4591, 1129, 2281, 4592, 4593, 3671, 4594, 5385, 1130, 2284, 6035, 6037, 2290, 2291, 6038, 537, 2292, 2293, 6039, 539, 1638, 2294, 2295, 5391, 6040, 6041, 541, 1640, 2296, 2297, 2599, 2600, 2762, 6045, 543, 1642, 2298, 2299, 2601, 2602, 2764, 6049, 545, 1644, 2300, 2301, 2603, 547, 1646, 2302, 2303, 4635, 6053, 2605, 2304, 2305, 2306, 2307, 2308, 2309, 2310, 2311, 3714, 4642, 2312, 2313, 549, 1151, 1649, 2315, 6054, 551, 1152, 1650, 2316, 3717, 4647, 6055, 2318, 2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 1652, 1653, 3723, 4658, 2328, 2329, 1654, 1655, 3724, 1167, 1656, 1657, 2330, 2331, 3725, 5408, 1169, 1658, 1659, 2332, 2333, 3726, 1660, 1661, 2334, 2335, 2609, 3729, 4660, 5409, 6056, 5411, 1172, 1173, 2769, 2337, 1662, 1663, 2338, 2339, 2612, 2613, 3733, 4665, 6058, 1175, 1664, 1665, 2341, 1176, 1666, 2343, 1178, 1179, 1667, 1668, 2616, 2617, 2770, 3736, 4668, 4669, 4670, 4671, 6060, 4672, 4673, 1182, 1183, 1669, 1670, 2350, 2618, 2772, 3746, 4674, 4675, 6063, 4676, 4677, 6065, 2354, 4678, 6600, 4679, 4680, 4681, 4682, 1195, 2359, 2621, 2622, 2773, 6070, 1196, 6074, 1198, 1199, 3767, 2624, 1200, 1671, 1672, 3769, 3770, 3771, 3772, 2626, 3773, 1201, 1202, 1203, 1674, 3774, 4791, 5491, 6616]
Size after drop: (4106, 14)

In [10]:
dforch

,track number,track name,channel,program,onset in quarter notes,duration in quarter notes,pitch,velocity,transpose_{'n_semitones': 12},transpose_{'n_semitones': 24},transpose_{'n_semitones': 46},transpose_{'n_semitones': -12},transpose_{'n_semitones': -24},transpose_{'n_semitones': -46}
0,1,Flute,1,73,0.0,2.0,82,60,True,False,False,False,False,False
1,1,Flute,1,73,0.0,2.0,88,60,True,True,False,False,False,False
1206,3,Clarinet,3,71,0.0,2.0,67,60,True,False,False,False,False,False
1675,4,Bassoon,4,70,0.0,2.0,48,60,False,False,False,True,False,False
2775,9,Violin,10,40,0.0,2.0,67,60,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4789,10,Violin,10,40,1570.0,4.0,60,60,False,False,False,False,False,False
4790,10,Violin,10,40,1570.0,4.0,68,60,False,False,False,False,False,False
1204,2,Oboe,2,68,1574.0,1.0,75,60,True,False,False,False,False,False
1205,2,Oboe,2,68,1574.0,1.0,79,60,True,False,False,False,False,False
6080,12,Violoncello,12,42,1574.0,1.0,46,60,True,False,False,False,False,False

In [11]:
df_reduced

,track number,track name,channel,program,onset in quarter notes,duration in quarter notes,pitch,velocity,transpose_{'n_semitones': 12},transpose_{'n_semitones': 24},transpose_{'n_semitones': 46},transpose_{'n_semitones': -12},transpose_{'n_semitones': -24},transpose_{'n_semitones': -46}
0,1,Flute,1,73,0.0,2.0,82,60,True,False,False,False,False,False
1,1,Flute,1,73,0.0,2.0,88,60,True,True,False,False,False,False
1206,3,Clarinet,3,71,0.0,2.0,67,60,True,False,False,False,False,False
1675,4,Bassoon,4,70,0.0,2.0,48,60,False,False,False,True,False,False
2775,9,Violin,10,40,0.0,2.0,67,60,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4789,10,Violin,10,40,1570.0,4.0,60,60,False,False,False,False,False,False
4790,10,Violin,10,40,1570.0,4.0,68,60,False,False,False,False,False,False
1204,2,Oboe,2,68,1574.0,1.0,75,60,True,False,False,False,False,False
1205,2,Oboe,2,68,1574.0,1.0,79,60,True,False,False,False,False,False
6080,12,Violoncello,12,42,1574.0,1.0,46,60,True,False,False,False,False,False

In [12]:
df_reduced[df_reduced["transpose_{'n_semitones': 46}"]==True]

,track number,track name,channel,program,onset in quarter notes,duration in quarter notes,pitch,velocity,transpose_{'n_semitones': 12},transpose_{'n_semitones': 24},transpose_{'n_semitones': 46},transpose_{'n_semitones': -12},transpose_{'n_semitones': -24},transpose_{'n_semitones': -46}
329,1,Flute,1,73,419.0,1.0,84,60,True,True,True,False,False,False

In [13]:
save_midi_with_exact_timing_structure(df_reduced, 'midis/example_reduced.mid', reference_midi_path=fileorch)

=== SAVING WITH EXACT TIMING STRUCTURE ===
Extracting timing structure from midis/liszt_classical_archives-0/orchestra.mid
ticks_per_beat: 1024
Found 0 timing events:
Using ticks_per_beat: 1024
Applying key signature fix for MuseScore compatibility...
✓ Added consistent key signatures to 10 instrument tracks
✅ Saved midis/example_reduced.mid with exact timing structure preserved
   - 0 timing events preserved
   - 10 instrument tracks created
   - Key signatures fixed for MuseScore compatibility

In [14]:
from xgboost import XGBClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

import numpy as np
import time
import joblib

KERAS_AVAILABLE = False

def estimate_transform(df, ytarget="transpose_{'n_semitones': 12}", model="XGBoost", pipeline_path=""):
    """
    FM
    """
    
    # Define available classifiers and their names
    classifiers_map = {
        "XGBoost": XGBClassifier(),
        "RandomForest": RandomForestClassifier(),
        "DecisionTree": DecisionTreeClassifier(),
        "NearestNeighbors": KNeighborsClassifier(1),
        "MLP3": MLPClassifier(hidden_layer_sizes=(128, 128, 128)),
        "NaiveBayes": GaussianNB(),
        "MLP1": MLPClassifier(),
        "AdaBoost": AdaBoostClassifier(),
    }
    
    if KERAS_AVAILABLE:
        classifiers_map["LSTMClassifier"] = KerasClassifierWrapper(build_lstm_classifier)
        classifiers_map["TransformerClassifier"] = KerasClassifierWrapper(build_transformer_classifier)

    # Check if the requested model is available
    if model not in classifiers_map:
        if "LSTMClassifier" in model or "TransformerClassifier" in model:
            print(f"Error: Keras is not available. Cannot use {model}.")
            return
        else:
            print(f"Error: Invalid model name '{model}'. Available models are: {list(classifiers_map.keys())}")
            return
            
    clf_name = model
    clf = classifiers_map[clf_name]

    # Load and process source file
    print(f"Learning {ytarget}")
    df = df.sort_values(
        ['onset in quarter notes', 'duration in quarter notes', 'track number'],
        ascending=[True, True, True]
    )
    nmat = df.to_numpy()
    mapping = learn_quaterna_mapping(nmat, ytarget)
    print("Mapping:", mapping)
    
    X, _ = defineXy(nmat, ytarget)
    y = df[ytarget].to_numpy()
    print("Labels", np.unique(y))
    print("Number of events:", X.shape[0])
    print("Last onset at", X[X.shape[0] - 1, 0])

    if len(np.unique(y)) == 1:
        print("Only one label in target variable")
        return
    
    # Partition the dataset
    X_train, X_test, y_train, y_test, le = split_and_encode(X, y, test_size=0.2, random_state=42)
    X_train_f, _, y_train_f, _, le_f = split_and_encode(X, y, test_size=0, random_state=42)
    
    # Train and predict with the specified classifier
    print(f"\n--------- {clf_name} ---------")
    start = time.time()
    
    if clf_name in ["LSTMClassifier", "TransformerClassifier"]:
        clf_pipeline = make_pipeline(StandardScaler(), clf)
    else:
        clf_pipeline = clf
        
    clf_pipeline.fit(X_train, y_train)
    score = clf_pipeline.score(X_test, y_test) # This is accuracy (?)
    # TODO: Here and everywhere, use more scoring functions (prec, rec, f1, acc)
    end = time.time()
    
    print("Train Time (sec):", f"{end - start:.4f}")
    print("Score on Test (20%):", f"{score:.4f}")
    #
    # Save all needed artifacts
    if pipeline_path!="": 
        artifact = {
            "pipeline": clf_pipeline,                 # pipeline
            "label_encoder": le_f,           # label encoder for final training
            "mapping": mapping,              # quaterna reconstruction mapping
            "ytarget": ytarget,              # 
            }

        joblib.dump(artifact, pipeline_path)
        print(f"[AMO-XGB SAVE] Pipeline saved: {pipeline_path}")
    #

In [ ]:
for func, kwargs in transformations:
    ytarget = f"{func.__name__}_{kwargs}"
    estimate_transform(df_reduced, ytarget=ytarget, model="XGBoost", pipeline_path="")
    print("\n")

# TODO: Use one model for multi-variate target prediction

Learning transpose_{'n_semitones': 12}
Mapping: [[1 'Flute' 1 73]
 [2 'Oboe' 2 68]
 [3 'Clarinet' 3 71]
 [4 'Bassoon' 4 70]
 [5 'Horn' 5 60]
 [6 'Trumpet' 6 56]
 [9 'Violin' 10 40]
 [10 'Violin' 10 40]
 [11 'Viola' 11 41]
 [12 'Violoncello' 12 42]
 [13 'Contrabass' 13 43]]
Labels [False  True]
Number of events: 4106
Last onset at 1574.0
y_train, test size: 0.2 , labels: [False  True]
y_train, test size: 0 , labels: [False  True]

--------- XGBoost ---------
Train Time (sec): 1.5259
Score on Test (20%): 0.8236


Learning transpose_{'n_semitones': 24}
Mapping: [[1 'Flute' 1 73]
 [2 'Oboe' 2 68]
 [3 'Clarinet' 3 71]
 [4 'Bassoon' 4 70]
 [5 'Horn' 5 60]
 [6 'Trumpet' 6 56]
 [9 'Violin' 10 40]
 [10 'Violin' 10 40]
 [11 'Viola' 11 41]
 [12 'Violoncello' 12 42]
 [13 'Contrabass' 13 43]]
Labels [False  True]
Number of events: 4106
Last onset at 1574.0
y_train, test size: 0.2 , labels: [False  True]
y_train, test size: 0 , labels: [False  True]

--------- XGBoost ---------
Train Time (sec): 0.4277
Score on Test (20%): 0.9246


Learning transpose_{'n_semitones': 46}
Mapping: [[1 'Flute' 1 73]
 [2 'Oboe' 2 68]
 [3 'Clarinet' 3 71]
 [4 'Bassoon' 4 70]
 [5 'Horn' 5 60]
 [6 'Trumpet' 6 56]
 [9 'Violin' 10 40]
 [10 'Violin' 10 40]
 [11 'Viola' 11 41]
 [12 'Violoncello' 12 42]
 [13 'Contrabass' 13 43]]
Labels [False  True]
Number of events: 4106
Last onset at 1574.0
y_train, test size: 0.2 , labels: [False  True]
y_train, test size: 0 , labels: [False  True]

--------- XGBoost ---------
Train Time (sec): 0.0688
Score on Test (20%): 1.0000


Learning transpose_{'n_semitones': -12}
Mapping: [[1 'Flute' 1 73]
 [2 'Oboe' 2 68]
 [3 'Clarinet' 3 71]
 [4 'Bassoon' 4 70]
 [5 'Horn' 5 60]
 [6 'Trumpet' 6 56]
 [9 'Violin' 10 40]
 [10 'Violin' 10 40]
 [11 'Viola' 11 41]
 [12 'Violoncello' 12 42]
 [13 'Contrabass' 13 43]]
Labels [False  True]
Number of events: 4106
Last onset at 1574.0
y_train, test size: 0.2 , labels: [False  True]
y_train, test size: 0 , labels: [False  True]

--------- XGBoost ---------
Train Time (sec): 0.2647
Score on Test (20%): 0.9380


Learning transpose_{'n_semitones': -24}
Mapping: [[1 'Flute' 1 73]
 [2 'Oboe' 2 68]
 [3 'Clarinet' 3 71]
 [4 'Bassoon' 4 70]
 [5 'Horn' 5 60]
 [6 'Trumpet' 6 56]
 [9 'Violin' 10 40]
 [10 'Violin' 10 40]
 [11 'Viola' 11 41]
 [12 'Violoncello' 12 42]
 [13 'Contrabass' 13 43]]
Labels [False  True]
Number of events: 4106
Last onset at 1574.0
y_train, test size: 0.2 , labels: [False  True]
y_train, test size: 0 , labels: [False  True]

--------- XGBoost ---------
Train Time (sec): 0.2246
Score on Test (20%): 0.9964


Learning transpose_{'n_semitones': -46}
Mapping: [[1 'Flute' 1 73]
 [2 'Oboe' 2 68]
 [3 'Clarinet' 3 71]
 [4 'Bassoon' 4 70]
 [5 'Horn' 5 60]
 [6 'Trumpet' 6 56]
 [9 'Violin' 10 40]
 [10 'Violin' 10 40]
 [11 'Viola' 11 41]
 [12 'Violoncello' 12 42]
 [13 'Contrabass' 13 43]]
Labels [False]
Number of events: 4106
Last onset at 1574.0
Only one label in target variable